### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

### ISSUE THREAD

**Issue by Normo** [ansible/ansible-lint-action#12]
#### Summary
When using the github action without any targets (to [auto-detect roles and playbooks](https://github.com/ansible/ansible-lint/issues/6139)), the job aborts with the following error:
```
+ ansible-lint -v --force-color
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/__main__.py", line 153, in main
    args = get_playbooks_and_roles(options=options)
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/utils.py", line 774, in get_playbooks_and_roles
    universal_newlines=True).split()))
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```
The related ansible-lint code section is probably https://github.com/ansible/ansible-lint/blob/9b1c30beb517ff33be10119c3b90182b8e56b23a/lib/ansiblelint/utils.py#L770.
I suppose the `git` cli needs to be installed as a dependency in the container image.

#### Configuration
I tried it with:
```yaml
name: CI

on: [push, pull_request]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Ansible-lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: ""
```

**Comment by Normo** [comment]
Okay, I just noticed that you have to specify the current directory (`./`) for auto-detection:
```yaml
    - name: Ansible-lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: "./"
```

**Comment by webknjaz** [comment]
FTR installing Git won't affect this action since it runs in a docker container and doesn't have access to things in the host VM.
