### ISSUE TITLE
override-deps from README not working

### ISSUE THREAD

**Issue by srl295** [ansible/ansible-lint-action#39]
0thly,  Thanks for this action! 👍 

1st, the  override-deps from the README don't work anymore.

```yaml
        override-deps: |
          ansible==2.9
          ansible-lint==4.2.0
```

https://github.com/ansible/ansible-lint-action/blame/6c8c14186662e43effbe39a678950896a46799ad/README.md#L40-L42

produces an error. the workaround is to remove those deps.

https://github.com/unicode-org/cldr/pull/729

failure:

```
/usr/bin/docker run --name e334689e305fd76304acfbf8761dad0103c5a_ee12aa --label 9e3346 --workdir /github/workspace --rm -e INPUT_TARGETS -e INPUT_OVERRIDE-DEPS -e INPUT_ARGS -e TARGETS -e OVERRIDE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cldr/cldr":"/github/workspace" 9e3346:89e305fd76304acfbf8761dad0103c5a  ""
+ args=("$@")
+ '[' /entrypoint.sh = /entrypoint.sh ']'
+ echo -E '\nRunning Ansible Lint...\n'
\nRunning Ansible Lint...\n
+ ansible::lint ''
+ : 'tools/scripts/ansible/setup-playbook.yml
'
+ : /github/workspace
+ pushd /github/workspace
+ override_python_packages
+ [[ -n ansible==2.9
ansible-lint==4.2.0
 ]]
+ pip install ansible==2.9 ansible-lint==4.2.0
/github/workspace /github/workspace
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible==2.9
  Downloading ansible-2.9.0.tar.gz (14.1 MB)
Collecting ansible-lint==4.2.0
  Downloading ansible_lint-4.2.0-py2.py3-none-any.whl (57 kB)
…
2020-09-23T00:05:23.1094326Z Successfully built ansible
2020-09-23T00:05:23.2282784Z Installing collected packages: ansible, ansible-lint
2020-09-23T00:05:23.2283751Z   Attempting uninstall: ansible
2020-09-23T00:05:23.2285484Z     Found existing installation: ansible 2.10.0
2020-09-23T00:05:28.3595731Z     Uninstalling ansible-2.10.0:
2020-09-23T00:05:28.9364025Z       Successfully uninstalled ansible-2.10.0
2020-09-23T00:05:39.8302418Z   Attempting uninstall: ansible-lint
2020-09-23T00:05:39.8303276Z     Found existing installation: ansible-lint 4.3.5
2020-09-23T00:05:39.8469732Z     Uninstalling ansible-lint-4.3.5:
2020-09-23T00:05:39.8608436Z       Successfully uninstalled ansible-lint-4.3.5
2020-09-23T00:05:39.9195639Z Successfully installed ansible-2.9.0 ansible-lint-4.2.0
2020-09-23T00:05:40.7911654Z + pip check
2020-09-23T00:05:40.9423622Z WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
2020-09-23T00:05:41.0484520Z No broken requirements found.
2020-09-23T00:05:41.0695722Z + echo 'Completed installing override dependencies...'
2020-09-23T00:05:41.0699570Z Completed installing override dependencies...
2020-09-23T00:05:41.0700255Z + local opts
2020-09-23T00:05:41.0703959Z ++ parse_args
2020-09-23T00:05:41.0704161Z ++ local opts=
2020-09-23T00:05:41.0704333Z ++ ((  0  ))
2020-09-23T00:05:41.0714682Z ++ eval set -- ''
2020-09-23T00:05:41.0714981Z +++ set --
2020-09-23T00:05:41.0715237Z ++ echo ''
2020-09-23T00:05:41.0715421Z ++ return 0
2020-09-23T00:05:41.0715603Z + opts=
2020-09-23T00:05:41.0715895Z + shopt -s globstar
2020-09-23T00:05:41.0716425Z + ansible-lint -v --force-color tools/scripts/ansible/setup-playbook.yml
2020-09-23T00:05:41.6188952Z Traceback (most recent call last):
2020-09-23T00:05:41.6190281Z   File "/usr/local/bin/ansible-lint", line 5, in <module>
2020-09-23T00:05:41.6190877Z     from ansiblelint.__main__ import main
2020-09-23T00:05:41.6191696Z   File "/usr/local/lib/python3.8/site-packages/ansiblelint/__init__.py", line 29, in <module>
2020-09-23T00:05:41.6192330Z     import ansiblelint.utils
2020-09-23T00:05:41.6193105Z   File "/usr/local/lib/python3.8/site-packages/ansiblelint/utils.py", line 41, in <module>
2020-09-23T00:05:41.6193842Z     from ansible.parsing.mod_args import ModuleArgsParser
2020-09-23T00:05:41.6194719Z   File "/usr/local/lib/python3.8/site-packages/ansible/parsing/mod_args.py", line 26, in <module>
2020-09-23T00:05:41.6195465Z     from ansible.plugins.loader import module_loader, action_loader
2020-09-23T00:05:41.6196571Z   File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 25, in <module>
2020-09-23T00:05:41.6198088Z     from ansible.utils.collection_loader import AnsibleCollectionLoader, AnsibleFlatMapLoader, AnsibleCollectionRef
2020-09-23T00:05:41.6201271Z ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.8/site-packages/ansible/utils/collection_loader/__init__.py)

```

**Comment by mattwillsher** [comment]
I've started to see the same issue in the last few days - it was working 2 days ago, now I get the above - https://github.com/willshersystems/ansible-sshd/actions/runs/268230076

It seems to be the same cause as https://github.com/ansible-collections/community.kubernetes/issues/135, the fix for which was:

```
    pip3 uninstall ansible
    rm -rf /usr/local/lib/python3.7/site-packages/ansible (things that weren't automatically removed)
    pip3 install ansible
```

**Comment by srl295** [comment]
@mattwillsher For me I have no reason to pin to a pre 2.10.0 Ansible, so just letting the current get installed (from the package manager) was fine.

**Comment by ssbarnea** [comment]
No longer valid for version on main branch.
