### ISSUE TITLE
ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader'

### ISSUE THREAD

**Issue by vinovarov** [ansible/ansible-lint-action#40]
Hi everybody,

while running `ansible lint` in a container at GHA I receive error:

```
+ ansible-lint -v --force-color playbooks/haproxy-api-yc/production/set-config.yml playbooks/haproxy-api-yc/staging/set-config.yml playbooks/haproxy-cdp/set-config.yml playbooks/haproxy-micros/set-config.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__init__.py", line 29, in <module>
    import ansiblelint.utils
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/utils.py", line 41, in <module>
    from ansible.parsing.mod_args import ModuleArgsParser
  File "/usr/local/lib/python3.8/site-packages/ansible/parsing/mod_args.py", line 26, in <module>
    from ansible.plugins.loader import module_loader, action_loader
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 26, in <module>
    from ansible.utils.collection_loader import AnsibleCollectionLoader, AnsibleFlatMapLoader, AnsibleCollectionRef
ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.8/site-packages/ansible/utils/collection_loader/__init__.py)
```

Re-runs do not help, the issue appears to be somewhere in docker image.

**Comment by dadav** [comment]
Might not be a solution for you, but this seems to fix it:
https://github.com/ansible-collections/community.kubernetes/issues/135#issuecomment-661189940

**Comment by vinovarov** [comment]
Thank you @dadav, appears to be true - fixing Ansible version from `2.9.11` to `2.10.0` in `<repo>\.github\workflows\Ansible lint.yml` seems to help:

```
jobs:
  lint:
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          override-deps: |
            ansible==2.10.0
            ansible-lint==4.2.0
```
