### ISSUE TITLE
No such file or directory: 'ansible': 'ansible'

### ISSUE THREAD

**Issue by stiliajohny** [ansible/ansible-lint-action#50]
After Updating on the latest version ( at the time of the issue raised ) I am getting some errors 

My current action is under https://github.com/stiliajohny/Ansible-Provisioning/blob/master/.github/workflows/ansible-lint.yml

which I am using 
```yaml
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v4.1.0.post0
```

I am getting the following error [Raw Log from Action](https://pipelines.actions.githubusercontent.com/1nazh2pv7eNHKMbguFYdpOdCSuHSmu7jIFaZwjmUn71G3amNIW/_apis/pipelines/1/runs/574/signedlogcontent/3?urlExpires=2021-03-08T20%3A03%3A57.3168671Z&urlSigningMethod=HMACV1&urlSignature=yx0pakrRNUfCyRY%2FPKqr8oS52IwIDynwKTok%2BCszyro%3D)

```log
2021-02-11T19:56:41.3451595Z + ansible-lint -v --force-color -x 204,403,301,305,701,401,303,208,306 ./pull-provisioning-configuration.yml ./pull-provisioning-execution.yml
2021-02-11T19:56:41.5662128Z Traceback (most recent call last):
2021-02-11T19:56:41.5663809Z   File "/usr/local/bin/ansible-lint", line 5, in <module>
2021-02-11T19:56:41.5664531Z     from ansiblelint.__main__ import _run_cli_entrypoint
2021-02-11T19:56:41.5665475Z   File "/usr/local/lib/python3.7/site-packages/ansiblelint/__main__.py", line 34, in <module>
2021-02-11T19:56:41.5666132Z     from ansiblelint import cli
2021-02-11T19:56:41.5666962Z   File "/usr/local/lib/python3.7/site-packages/ansiblelint/cli.py", line 18, in <module>
2021-02-11T19:56:41.5667692Z     from ansiblelint.file_utils import expand_path_vars
2021-02-11T19:56:41.5668626Z   File "/usr/local/lib/python3.7/site-packages/ansiblelint/file_utils.py", line 14, in <module>
2021-02-11T19:56:41.5669470Z     from ansiblelint.config import options
2021-02-11T19:56:41.5670353Z   File "/usr/local/lib/python3.7/site-packages/ansiblelint/config.py", line 103, in <module>
2021-02-11T19:56:41.5671074Z     if ansible_collections_path() in os.environ:
2021-02-11T19:56:41.5672197Z   File "/usr/local/lib/python3.7/site-packages/ansiblelint/config.py", line 71, in ansible_collections_path
2021-02-11T19:56:41.5673033Z     if ansible_version() >= ansible_version("2.10.0.dev0"):
2021-02-11T19:56:41.5673965Z   File "/usr/local/lib/python3.7/site-packages/ansiblelint/config.py", line 90, in ansible_version
2021-02-11T19:56:41.5674685Z     stderr=subprocess.PIPE,
2021-02-11T19:56:41.5675258Z   File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
2021-02-11T19:56:41.5675857Z     with Popen(*popenargs, **kwargs) as process:
2021-02-11T19:56:41.5676456Z   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
2021-02-11T19:56:41.5677040Z     restore_signals, start_new_session)
2021-02-11T19:56:41.5677802Z   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
2021-02-11T19:56:41.5678487Z     raise child_exception_type(errno_num, err_msg, err_filename)
2021-02-11T19:56:41.5679380Z FileNotFoundError: [Errno 2] No such file or directory: 'ansible': 'ansible'
```

Any help would be appreciated

**Comment by stiliajohny** [comment]
UPDATE: 
It seems to be working after I commented out 
```yaml
#        override-deps: |
#          ansible==2.9
#          ansible-lint==4.2.0
```

yet on the @master branch readme, it is mentioned that it shouldn't be commented out
